language: none
sudo: required

deploy:
  provider: s3
  access_key_id:
   secure: xzaHTASQRwv60JrxhoTywy3GEpuBUu8hvOdmYSyRpCJjmsvMhLKDBPvt8r/lnnbPyNkofqajAGFjcnfqq2wN9TVgXmfhr8TSRYuu25g0OOK47a+jqfDzUHzR2FbDsX1iz8cXledK3hUWGBLeJh/z65GLefIVdEB5AeZWzaJK1k/OP49If/RspBfKDkDNOHQ1KrFAySyAS/aDFUzF/OCCkdyn5ZGJl9yQouqmaUQJHqy4Hjo/aF49AriVf0Hp/XQa7nwcValpkspR7KHdgAWN1cIgawkR0cTnXSA3m3vYcz4mjxyFZOm7sy1RiRt6IexUctOtWUSnMqtHJvMpamM8b4qZ5K4zs9z5CMpNQgL9TCBTMZQHAHZIc0ZBAbx3UVbQG74igmAKa1qcNrrdffRmqEArw5SunHKK4dpLNBwewwbtA+8NJoTNArdAIY1FyCCb56O6/eg34mYt/WyfWYDUqfXXLDF8+zacD77HL5UXGAAouXTmmsxdthiBW9yKteQ8oLvsrvDBKUrzBmiv9z2GcFQoe9EV6KyDveg88inTLw8h0BTD9OBn3ufXOvE3luXu/vpEzDGX4luTHLszh1BHApAFbZKFfZ8h2beKHLpvY7PE8l3BNLI7tAtoukpznuE/Aw/2m2yKpNLsNjvFK4BkAYoSvffX1AY+3R+RujW+/AM=
  secret_access_key:
    secure: ButUXmTTpVebOI1REMQ7ofS6Y8NJDdOJz8HszSm1jQPpsIBuXIGx0itDp9KNIbxLRjYTHiM7c138by3hLseA0kgyRYcij4BzOSYE9r/pRKR4sH0F2GZMxLHjH0hDOMwF4zEvvaQxE4VxsomGS+xUK6tVolrIvOvhMldQvVgAbdfxftd8MxKAdGB7Z07YJraJOIUPAmIOobmvzNbCpPJS460iWzdoBB3X4oQ7qJgMo6aP22KzCMfdS9efSwhW30OyZl7xLXJ1Tb1l/C4wwPUR1MAANhoUcFrc7BrCnt9WyWhKa9DqsFCYUtiC+Ov7BHg7N6A/ZOKI6ospN9AHgARjOeExCwvPMzZCnP09mjQGQ72Cwd60KotVfDIgKorGnSdAJE+ftK4AE8V6Ij6NukG8Yy7Holm+mX48yqTuqdAen9e0yw04Ur6l1EJUcG8+Tk588EJJDWbPCQtOqy4XUEUpzG91xUp3ZY5gwRxCDFEHuQGm2oIdKS4r/s7pZ4kDh8CefIkwwOVfwFnIhY6U0FrVDFaYXh6+P2TzG3LTcLQOsI7fW76LGbPKU14zFODayx58kxaXPhOhX5Oul4njK6fsaO3o2YpTBX1kGbvCtwc31syi2Lexd0DctBkdGg80ORWnE/LkUoY0Ur0sMeCKUFSfre4NaoLRKukLEwZZ5mqt5SE=
  bucket:
    secure: yA2UWkilxl3Iqh1BInIdi+mf8Ew08e0jI5yOZ7sq1+S30DXapZWbQQIOtP2BCHLG/OzWTp6TadrYaYX0W5iXVgZr8JeP85U/wGSml6MjcJCgHPYmx6zMIVHlJ6PsSlc02fGgUlAMzSjJHzUv1aQPdmv12Xnwoqkgc2v/LU+yRnW4jKX3NwZHgZCFhxm+julK/TXKUY6ZrNXuU3l1gfDeZXawCcmo4c0x/MdOmUsEEH/2bHr9gzpUualAXYgCumQbbaHkM5EYxIcb+hSp76uwPZ2f26njR/c2xOMSSDOVbhMIQIOHl1qWgkW1aLE/rmxkUJ9d5r66Q5KWu58d8AfWe+XQ/YmtycB7KUORsFNvLrz8/4RU5wdOq9ftugBAnf4MlQC9sR4P32EBvmH4GLNhL9BkYgp//6MmY2/yF6eEL1f8vGurybxlEIvzydZvkY9i6UgWidnkEQDDYkiH7iADCi3/c3Rgn5ro+zeeKjLOBw9YmdvKF8ESW3Uxgrf1FVQo+0amsvccXXs+jTEg48apfcrq77YSyg7GKZjXgfaqF4ymfVPbH2uuNhfvH7wie7eNKUKsdXFgnx15cEvez3zXICeUZs2RLvjjYE3O4A5/ko8REeuhKJq9FsVrniWUFsBiOZSDjGXlXN9SF64NCwsqlWbbDyRnq9zPIBgIlnN5kKU=
  skip_cleanup: true
  region: ca-central-1
  local_dir: deploy
  upload-dir: terminology-themes

addons:
  apt:
    sources:
    - sourceline: 'ppa:niko2040/e19'
    packages:
    - libefl-bin

script:
  - make
  - sudo make install

before_deploy:
  - mkdir deploy
  - cp themes/*.edj deploy
