language: none
sudo: required

deploy:
  provider: bintray
  file: "bintray.json"
  user: "sylveon"
  key:
    secure: "G6qbgSK5BNEikCA1z324e0pWA2suySW2ZUFF94SzP1UV/+LQ8o+44KC8Jr2otYPFCRNRGBfQz96dIBkMV6XbPOvUCtwPgUViPOiaNsCW4xoncYp/mBAZlyWtHQnf81FmFX8CLiSD6rObo4fi5rnIYTzjVdy3sZazdLuMgDyxSwLSN6oebVQREGxSQTccp7VAdJukAJZNuQLpVXPPRDNkWDH82QpKx6bZnWaCRyB6O4kSRaqM3w3zuSl5iYEx8NVCjQ0IeMMQk1/r8oq/XaTgE/mF4r2sBEpIh53MrXAwIVaNBA85HOYw7qvj61cPPNxci1gud3ynHFhuMbtNd5UNDCrnDGTkSSTbJKZqpqIW5vgM4cQgU6beN7PQxSg7Sel0SEM9dWPIoRjiNm+49fHp8rp4LSD7006xJJmdugON2/F8jQLR516AeM+/4I0OvWwKE4UfZZ1lG88QeCaMmItZWhkju2ElEkTBKRnmp74VAgwVuU4SmT1/ASsSOLlxVzCn7Pc7bwfv1haYQfXrFHYCgIXGWbYfPZOBGhDRYHbXbVuUoOuclSYMEkBaC0WM4HIPHAWU2SDdB9eFVLsFcCdp4b0qeBDItTI4Ch+9iTGHa0Tci9atQcDFKq/xt/QeKDJ884+U211uGeK/suSW7tQmcnhlC2qxJwNq7qTTW+ZsEv0="
  passphrase:
    secure: "NIQfqds1kj3UWi/xe/ek5l3OdNQTWXveU76+Wr0y8u4gU6ISmpSQZBuKhlWvrZ7Z6byV4hbPf10wNwaWX31f1er+eDO/HvFithI9Xn/y/ufJVLD/yLIUj84a3KybdFWv8gBXK0YUNrmZClxpM2k8rb/dYL80bJ37iDPhz/W2ajCwqw4H6L1FqtzDycjcgCffnGgYtrsJ15f4ODRincC9trbYWpjSnLBINVkZJkk30lQlRtCM2RQk1hARFs0TrWtiyLKOB8xcxgln8R2642HEYRETKQr8tUh0fpV+0vycrembDXrMMlDEAJiseUNOAuwEdvejRScqRldyevtB9xRwysLa5vK7wJingfuMgo/Rk9hbzH+zlSTE/t8hMupgMBZa/5F7kqm3T3zIziCpDzH5T1XF/CgNfF5CkSRJEN66XpOkTyoTG69mshERi2sJxwt0T73LfIdmT2Puxumq1mTHTK7LJ2hD7JWshSG9fsherkvdS6v7iBmZfOU+Sb7FfJU32wr9dHFxHKMr8eVWpBtGvpON9ptZ6Q7eZwzTPvo8DNEe4TfqdhJspYy4auT8mv/AC2cpzj2D85s6YZgkOxNlKa0mbDUqtZd/xEgo9loHs3kvPPqB4WbGtVQQjadJV+WRiLAoLUiYL2FZXeg35y30kBMGpV+wIsOa81V+W8yfiME="

addons:
  apt:
    sources:
    - sourceline: 'ppa:niko2040/e19'
    packages:
    - libefl-bin

script:
  - make
  - sudo make install
