language: python
python: 3.6
install: pip install awscli
sudo: required

env:
  global:
    - secure: zrcl5rQQvSHRvJgpsA36UsfqNyrGKIJQww1s0i60EK9n9AanKThStKMTu5dCZI2xvKT8eoPEjqP8o2Fg9lJJ6aYo1Opgxz9WDM0LFQimaeQIPuL4lAmggO/lr0mK7zlqHfZqrlqsg5O2pOGkXkqCDxEqlEC2S9kLka4QIfSrp2Rs8kPhEfoWnN4LEzwCMdmVr9+/g66ogBk6iZpn9N02JEV06oxRjR7iAyl061enlTqyC2ZMzJyMm4eI+Y2aOYyj/X8uDURCtCxMkwHpvqMu6EegMcidNpEqHf6/GrLgd6Fvv3TtQD84SG6oxuMPwbiI0oBtxNj6LlE2t88Qn7HfXWdmQNr72k8pziGOA7f9TL134l0yCd+bAxIBKKXGKXjN2f5WrwvIyC22nbU7Ie2O6YPsb7XMUNdeNGxYw4WX2tm9lBOOHjmsZEuzdwnKFFI9uxxq+tKg5ODaHH/0pMB17Vtz/wuu2mdlIgHWwqahc3pNVXsrAAtq9EcvQVd54LkFnpcOrNlqOR0C8MsMiCijUngdJNpfwA/0zxry+n7w1ZVH20JU2hsgORx6+KrVblXw7ib6YnHbdd6lWx3VbM8VNUlds0EzRWxLZrPTgiR9Xc43Z7ngEVZUO/MUtlJscxrSCVF9HjLZSHetEOfE/iL91tI49U5T+q+ETKTrOkRee4s=
    - secure: TPgxMfaM9ABj/38Pa4dNBEqgWOLn4iMwDRZGvFj/bFUbv54ExliU8cVfB0Ft77wKsIZwoar8kkMXy7O3TJvxUANoajawf1hurdwIy/ktnBY/j74Gmu1wYpwRI0ZSXOUGcZ50zfhwXtpYRbvnP0S7MQ5IrWCoF7eto37fWXMRAZSKTyIOXNffT8tCXlnXBHOzuMGq1ULj9kkO13rDqGg3O3KfM5Oktra2Zxj6qY/W9Amx9GJq+sNx6Xj35AWqKnvCUGhGeuhD508AHcFV0D/hdEG3ZwrHdC4EQT8A7RSNB3eqibowYnLQ1dhnm1V+M9Ap+hhKF/nchtI1BivMa0qu0Ogy6WBRzEkhg7Qsaqzdmi3yTTT/xM3PxC6bQnxEapl4LV13vOSZ7KkWWsko5GSaczaHD+sL5mxh5ZS9YrxMFAxHgdKA2UMrNteMK1pMw//BZGM9NXePOgD2bj361G8YzNrfgeWIYrDrZtxqKOCoI+5KA9t7fhce1LSQ23zmkyuL4KbOVy5OgfgaHUj7HZIv5CN+pZm/gdMj3nhLFRB02R13RW4nJvlUJid7jrgSRoibhHfsb38vFeXgffm7xMaVFTg2S9SgbtXzb2Uu3T9uabwnpq1dXzZDA0i9gKRrBGwRH9fzSIHSEt/mVpouiVg/d3j2P9EoH0x+z/VJHGAlRVo=
    - secure: IT9IcoMlhOmlWcLGxNryEhaHVcXHBCWSTpVZqOaO+csza+alBxF8RFqF03Xk4iqGOep/FubioGP0/bpDyouENdqVzcME9OX4MuTn7tHLkNjYsZb8CmaWD/wPpjWv5osy/Fq5DfiGUy47SmBF1yyOLzxlm+kJeiIuOJZwGONBt83KfhYZzTGYCXUH85QaeRFltdtlwgXyYtlwu76acBXDBxFJ/SfsA6rZZg1fhgLZoGVik71BQ2lj+IZIPXn2aeGaNb8FhdCVjduDtt3a4QY1jtXt/GI7aaxRxx+cIbI+f1i8eSoujVSJzZEPXPpFI8ZXJpDxBYgIoWpr8CnbQcGTa1znNW5W/UAd+q6NM+zBKztUGh+ItJC7nA7Z8lfbUAts4K6ZOsAukIP5qrCa4dTjYp78T7bMufmfBWrBVNGL16YKhFds7qajfqE4dB8L9Bh2YhYFUjUTPFeGUabzI0e5sSvNOPuzsLKFoQeD5Jnb/I3Q98Cdu4/8h5FLGowWL/fUtxt0LT6oAXH9y0lAYG4FYRTDA9mrsWNJk34YgNuvr4liavGdMk03WDDkHs2pLFuDLnzxVApirYijohq+giAI0k9zFNUNDrhhHRqwGw/STtlHMJ+Z3N+Alc8rrIJEFZEKClC7Bou9PwUDmRM9ptMzyeDaQM2b2rHbzSEC0MqaLpo=

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket:
    secure: yA2UWkilxl3Iqh1BInIdi+mf8Ew08e0jI5yOZ7sq1+S30DXapZWbQQIOtP2BCHLG/OzWTp6TadrYaYX0W5iXVgZr8JeP85U/wGSml6MjcJCgHPYmx6zMIVHlJ6PsSlc02fGgUlAMzSjJHzUv1aQPdmv12Xnwoqkgc2v/LU+yRnW4jKX3NwZHgZCFhxm+julK/TXKUY6ZrNXuU3l1gfDeZXawCcmo4c0x/MdOmUsEEH/2bHr9gzpUualAXYgCumQbbaHkM5EYxIcb+hSp76uwPZ2f26njR/c2xOMSSDOVbhMIQIOHl1qWgkW1aLE/rmxkUJ9d5r66Q5KWu58d8AfWe+XQ/YmtycB7KUORsFNvLrz8/4RU5wdOq9ftugBAnf4MlQC9sR4P32EBvmH4GLNhL9BkYgp//6MmY2/yF6eEL1f8vGurybxlEIvzydZvkY9i6UgWidnkEQDDYkiH7iADCi3/c3Rgn5ro+zeeKjLOBw9YmdvKF8ESW3Uxgrf1FVQo+0amsvccXXs+jTEg48apfcrq77YSyg7GKZjXgfaqF4ymfVPbH2uuNhfvH7wie7eNKUKsdXFgnx15cEvez3zXICeUZs2RLvjjYE3O4A5/ko8REeuhKJq9FsVrniWUFsBiOZSDjGXlXN9SF64NCwsqlWbbDyRnq9zPIBgIlnN5kKU=
  skip_cleanup: true
  region: ca-central-1
  local_dir: deploy
  upload-dir: terminology-themes

addons:
  apt:
    sources:
    - sourceline: ppa:niko2040/e19
    packages:
    - libefl-bin

script:
  - make
  - sudo make install

before_deploy:
  - mkdir deploy
  - cp themes/*.edj deploy

after_deploy: aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFRONT_ID} --paths "/terminology-themes/*"
